on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release exe
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_Freeze  
      - name: Build with pyinstaller
        run: |
          # build exe in build folder
          python setup.py build

      - name: Upload using GitHub cli
        run: |
          # build single exe in dist folder
          choco install gh -y
          gh auth login --with-token $env:GITHUB_TOKEN
          Get-ChildItem env:
          Compress-Archive -Path build\exe.win-*\*.* -DestinationPath checkpath.zip          
          gh release upload $env:GITHUB_REF.Split('/')[2] checkpath.zip checkpath.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

